### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by kernelENREK** [TomGrill/gdx-twitter-app#1]
I translated the sample app using the latest libGDX version (1.8.0.0) and Android Studio 1.5.1 (Build  #AI-141.2456560)

The sample compile without errors but when you press loginButton i get this error:

```
E:\AndroidStudio\Projects\libgdx1\desktop\build\libs>java -jar desktop-1.0.jar
gdx-twitter: Skip loading Twitter API for Android. Not running Android.

gdx-twitter: gdx-twitter for Desktop loaded successfully.
gdx-twitter: Skip loading gdx-twitter for HTML. Not running HTML.

gdx-twitter: Skip loading gdx-twitter for iOS. Not running iOS.

feb 06, 2016 12:19:49 PM org.apache.http.impl.client.DefaultRequestDirector handleResponse
WARNING: Authentication error: Unable to respond to any of these challenges:
 {oauth=www-authenticate: OAuth realm="https://api.twitter.com"}
oauth.signpost.exception.OAuthNotAuthorizedException: Authorization failed (server replied with a 401). This can happen if the consumer key was not correct or the signatures did not match.
        at oauth.signpost.AbstractOAuthProvider.handleUnexpectedResponse(AbstractOAuthProvider.java:243)
        at oauth.signpost.AbstractOAuthProvider.retrieveToken(AbstractOAuthProvider.java:193)
        at oauth.signpost.AbstractOAuthProvider.retrieveRequestToken(AbstractOAuthProvider.java:74)
        at de.tomgrill.gdxtwitter.desktop.JXBrowserTwitterGUI.generateAuthUrl(JXBrowserTwitterGUI.java:65)
        at de.tomgrill.gdxtwitter.desktop.JXBrowserTwitterGUI.start(JXBrowserTwitterGUI.java:84)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$159(LauncherImpl.java:863)
        at com.sun.javafx.application.LauncherImpl$$Lambda$52/185014036.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$172(PlatformImpl.java:326)
        at com.sun.javafx.application.PlatformImpl$$Lambda$48/1149116394.run(Unknown Source)
        at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
        at com.sun.javafx.application.PlatformImpl$$Lambda$50/1979803811.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
        at com.sun.javafx.application.PlatformImpl$$Lambda$49/253045483.run(Unknown Source)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$145(WinApplication.java:101)
        at com.sun.glass.ui.win.WinApplication$$Lambda$38/553997588.run(UnknownSource)
        at java.lang.Thread.run(Thread.java:745)
com.mygdx.game.MyGdxGame: GUI Signin with error: Bad Request
com.mygdx.game.MyGdxGame: GUI Signin canceled
```

I have a twitter app since 5 years, Its working Ok since then.

I created MyTwitterConfig with the TWITTER_CONSUMER_KEY and TWITTER_CONSÜMER_SECRET from my 'twitter app' but always throw that authentication error.

Same error on Android project.

**Comment by TomGrill** [comment]
I will look into this in a few days, but please make sure your credentials are correct.

**Comment by TomGrill** [comment]
Ok I think found the issue:
Go to your Twitter App settings and DISABLE: "Enable Callback Locking (It is recommended to enable callback locking to ensure apps cannot overwrite the callback url)" option. The app must be able to manipulate the callback url to gain the access token.

I will add this to the readme
